version: '2.2'

services:
  detect-app:
    image: skpdi-detect-app
    build: .
    working_dir: /opt
    container_name: skpdi-detector
    command: python track.py --source  test_video/2021-11-22_11-27-22-_online-video-cutter.com_.mp4 --yolo-weights best.pt --img 640 --tracking-method strongsort --save-vid --conf-thres 0.7 --reid-weights osnet_x1_0_msmt17.pt --host ${YOUR_HOST} --port ${YOUR_PORT}
#    command: python track.py --source  rtsp://admin:admin@192.168.1.13:554/stander/livestream/0/0 --yolo-weights best.pt --img 640 --tracking-method strongsort --save-vid --conf-thres 0.7 --reid-weights osnet_x1_0_msmt17.pt --host ${YOUR_HOST} --port ${YOUR_PORT}
    networks:
      - app-network
    restart: always
    volumes:
      - ./model:/opt/model
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: skpdi_db
    networks:
      - app-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_skdpi
    expose:
      - 5432

volumes:
  postgres_data:

networks:
  app-network:
    name: skpdi_network
